// Delivery coordinates points 
enum E_DELIVERY_POINT
{
    Float:dPosX,
    Float:dPosY,
    Float:dPosZ,
    bool:visited
};

new DeliveryPoints[MAX_DELIVERY_POINTS][E_DELIVERY_POINT] =
{
    {2503.55, -2410.45, 13.62, false},
    {2615.67, -2382.29, 13.62, false},
    {2731.65, -2487.61, 13.65, false},
    {2529.95, -2529.23, 13.65, false},
    {2219.37, -2666.35, 13.53, false},
    {2231.62, -2414.66, 13.54, false}
};