#define FILTERSCRIPT

#define MAX_DELIVERY_VANS 3
#define DELIVERY_VAN_ID 482
#define DELIVERY_VAN_COLOR 0
#define DELIVERY_VAN_SPAWN_TIME 60

#define CP_CARGA_X 2795.012
#define CP_CARGA_Y -2487.018
#define CP_CARGA_Z 13.764
#define CP_CARGA_RADIO 3.0

#define MAX_DELIVERY_PACKAGES 3
#define MAX_DELIVERY_POINTS 6



#define INVALID_CHECKPOINT_ID  -1
#define INVALID_MAPICON_ID -1

#define DELIVERY_PAYOUT 3000

#define DELIVERY_VAN_INTERACT_DISTANCE 0.4
#define ALLOWED_PICKUP_PACKAGE_LIMIT 40.0
#define INDEX_ATTACHED_PACKAGE 2     
#define MODEL_PACKAGE_BOX 1220
#define DELIVERY_SUCCESS_DISTANCE 100.0
#define BOX_SCALE 1.0